"""Small OS boundary: check ownership before reading expensive clipboard payloads."""

from __future__ import annotations

import ctypes
import sys

PRIVATE_TYPES = frozenset(
    {
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    }
)


class ClipboardState:
    def __init__(self):
        self._last: int | None = None
        self._pasteboard = None
        self._user32 = None
        if sys.platform == "darwin":
            from AppKit import NSPasteboard

            self._pasteboard = NSPasteboard.generalPasteboard()
        elif sys.platform == "win32":
            self._user32 = ctypes.WinDLL("user32", use_last_error=True)
            self._user32.GetClipboardSequenceNumber.restype = ctypes.c_uint32

    def sequence(self) -> int | None:
        if self._pasteboard is not None:
            return int(self._pasteboard.changeCount())
        if self._user32 is not None:
            return int(self._user32.GetClipboardSequenceNumber()) or None
        return None

    def changed(self) -> bool:
        current = self.sequence()
        changed = current is None or current != self._last
        self._last = current
        return changed

    def forget(self) -> None:
        self._last = None

    def private(self) -> bool:
        if self._pasteboard is not None:
            return bool(PRIVATE_TYPES.intersection(self._pasteboard.types() or ()))
        return False

    def text(self) -> str | None:
        """None means use the toolkit fallback; empty string means no native text."""
        if self._pasteboard is not None:
            from AppKit import NSPasteboardTypeString

            return str(self._pasteboard.stringForType_(NSPasteboardTypeString) or "")
        return None

    def set_text(self, value: str) -> bool:
        if self._pasteboard is None:
            return False
        from AppKit import NSPasteboardTypeString

        self._pasteboard.clearContents()
        if not self._pasteboard.setString_forType_(value, NSPasteboardTypeString):
            raise OSError("could not set clipboard text")
        return True
